In [5]:
import sys
sys.path.append('../')

import numpy as np
from network_based_nearest_neighbors import NetworkBasedNeighbors

x = np.random.random_sample((100000, 20))
x.shape

(100000, 20)

In [6]:
index = NetworkBasedNeighbors(x, batch_size=2000)

Indexing ...
batch 50 / 50 done. computation time = 1370.713026 sec.
Indexing was done


In [7]:
query = x[0].reshape(1,-1)
k = 10
index._search_neighbors_dev(query, k=k)

(array([0.89704164, 0.90799825, 0.95204415, 0.96660691, 0.98256159,
        0.98437985, 0.98789984, 1.008208  , 1.02257042, 1.0312447 ]),
 array([  920, 56930,  9144, 65824, 53761, 29459,  6966, 86497, 90587,
        62266]),
 [(0, 1.4131814644575411, 0.4652330969420768),
  (1, 1.2325496342327267, 0.18063183022481444),
  (2, 1.1580276647577572, 0.07452196947496947),
  (3, 1.107163723830072, 0.0508639409276852),
  (4, 1.0808608063404017, 0.026302917489670286),
  (5, 1.058387328319242, 0.022473478021159732),
  (6, 1.0547612125727648, 0.0036261157464771987),
  (7, 1.0542355556638057, 0.0005256569089591157),
  (8, 1.0510823760481791, 0.0031531796156265557),
  (9, 1.0510823760481791, 0.0)],
 0.0029201507568359375)

In [8]:
index.search_neighbors(query, k=k)

(array([0.        , 0.77322308, 0.82760977, 0.82965853, 0.84291023,
        0.87394596, 0.89704164, 0.91032157, 0.95204415, 0.96660691]),
 array([    0, 75238, 80922, 60083, 90924, 56380,   920, 42725,  9144,
        65824]))

In [9]:
from sklearn.metrics import pairwise_distances
import time
k = 10
t = time.time()
dist = pairwise_distances(query, x).reshape(-1)
idxs = dist.argsort()[:k]
dist = dist[idxs]
t = time.time() - t
dist_avg = dist.sum() / dist.shape[0]

dist = pairwise_distances(query, x).reshape(-1)
idxs = dist.argsort()[1:k+1]
dist = dist[idxs]
dist_avg_except_self = dist.sum() / dist.shape[0]

print('time = {:f}\ndist avg = {:f}\ndist avg (wo self) = {:f}'.format(
    t, dist_avg, dist_avg_except_self))

time = 0.027378
dist avg = 0.774081
dist avg (wo self) = 0.866401


In [13]:
n_tests = 2000

step_counter = []
time_counter = []

for i in range(n_tests):
    query = x[i].reshape(1,-1)
    _, _, infos, time = index._search_neighbors_dev(query, k=k, max_steps=20)
    step_counter.append(len(infos))
    time_counter.append(time)

In [14]:
from collections import Counter

Counter(step_counter)

Counter({6: 35,
         7: 157,
         8: 380,
         9: 443,
         10: 369,
         11: 267,
         12: 154,
         13: 98,
         14: 36,
         15: 28,
         16: 16,
         17: 4,
         18: 8,
         19: 3,
         20: 2})

In [17]:
size, bins = np.histogram(time_counter, bins=20)

for b, e, s in zip(bins, bins[1:], size):
    print('| {:f} ~ {:f} | {} % | '.format(b, e, '%.2f'%(100*s/2000)))

| 0.001015 ~ 0.001292 | 7.75 % | 
| 0.001292 ~ 0.001569 | 34.45 % | 
| 0.001569 ~ 0.001846 | 23.30 % | 
| 0.001846 ~ 0.002122 | 17.65 % | 
| 0.002122 ~ 0.002399 | 9.90 % | 
| 0.002399 ~ 0.002676 | 3.05 % | 
| 0.002676 ~ 0.002953 | 1.65 % | 
| 0.002953 ~ 0.003230 | 0.70 % | 
| 0.003230 ~ 0.003506 | 0.60 % | 
| 0.003506 ~ 0.003783 | 0.35 % | 
| 0.003783 ~ 0.004060 | 0.10 % | 
| 0.004060 ~ 0.004337 | 0.20 % | 
| 0.004337 ~ 0.004614 | 0.05 % | 
| 0.004614 ~ 0.004890 | 0.05 % | 
| 0.004890 ~ 0.005167 | 0.10 % | 
| 0.005167 ~ 0.005444 | 0.00 % | 
| 0.005444 ~ 0.005721 | 0.00 % | 
| 0.005721 ~ 0.005998 | 0.00 % | 
| 0.005998 ~ 0.006274 | 0.05 % | 
| 0.006274 ~ 0.006551 | 0.05 % | 
